{@controller.item.name.lower@}:
    pattern: /{@controller.item.name.lower@}
    controller: {@controller.item.name.cap@}
{@controller.list.name.lower@}:
    pattern: /{@controller.list.name.lower@}
    controller: {@controller.list.name.cap@}
